export const products = [
  {
    product_id: 1,
    product_name: '有机小白菜',
    category: '蔬菜',
    price: 5.80,
    original_price: 8.00,
    images: ['/images/products/product1.jpg'],
    description: '新鲜有机小白菜，无农药残留，绿色健康，口感鲜嫩，营养丰富。',
    specification: '500g/把',
    stock: 50,
    sales: 328,
    origin: '山东寿光',
    farmer: { farmer_id: 101, farmer_name: '张农户', farmer_avatar: '/images/avatars/farmer1.jpg', verified: true },
    status: 'on_sale',
    created_at: '2025-01-01 08:00:00',
    updated_at: '2025-01-20 10:30:00'
  },
  {
    product_id: 2,
    product_name: '本地胡萝卜',
    category: '蔬菜',
    price: 4.50,
    original_price: 6.00,
    images: ['/images/products/product2.jpg'],
    description: '本地种植胡萝卜，富含胡萝卜素，清甜可口，适合煲汤或生食。',
    specification: '500g/份',
    stock: 80,
    sales: 456,
    origin: '山东寿光',
    farmer: { farmer_id: 101, farmer_name: '张农户', farmer_avatar: '/images/avatars/farmer1.jpg', verified: true },
    status: 'on_sale',
    created_at: '2025-01-02 09:00:00',
    updated_at: '2025-01-21 11:00:00'
  },
  {
    product_id: 3,
    product_name: '有机西兰花',
    category: '蔬菜',
    price: 8.90,
    original_price: 12.00,
    images: ['/images/products/product3.jpg'],
    description: '有机认证西兰花，花球紧实，口感爽脆，维生素C含量丰富。',
    specification: '300g/颗',
    stock: 45,
    sales: 289,
    origin: '山东寿光',
    farmer: { farmer_id: 102, farmer_name: '李农户', farmer_avatar: '/images/avatars/farmer2.jpg', verified: true },
    status: 'on_sale',
    created_at: '2025-01-03 10:00:00',
    updated_at: '2025-01-22 09:30:00'
  },
  {
    product_id: 4,
    product_name: '新鲜黄瓜',
    category: '蔬菜',
    price: 3.80,
    original_price: 5.00,
    images: ['/images/products/product4.jpg'],
    description: '新鲜采摘黄瓜，脆嫩多汁，无苦味，可直接凉拌或炒食。',
    specification: '500g/份',
    stock: 120,
    sales: 567,
    origin: '山东寿光',
    farmer: { farmer_id: 102, farmer_name: '李农户', farmer_avatar: '/images/avatars/farmer2.jpg', verified: true },
    status: 'on_sale',
    created_at: '2025-01-04 11:00:00',
    updated_at: '2025-01-23 12:00:00'
  },
  {
    product_id: 5,
    product_name: '有机菠菜',
    category: '蔬菜',
    price: 6.50,
    original_price: 8.50,
    images: ['/images/products/product5.jpg'],
    description: '有机种植菠菜，叶片翠绿，茎秆鲜嫩，富含铁质和维生素。',
    specification: '400g/份',
    stock: 60,
    sales: 345,
    origin: '山东寿光',
    farmer: { farmer_id: 103, farmer_name: '王农户', farmer_avatar: '/images/avatars/farmer3.jpg', verified: true },
    status: 'on_sale',
    created_at: '2025-01-05 12:00:00',
    updated_at: '2025-01-24 13:30:00'
  },
  {
    product_id: 6,
    product_name: '红富士苹果',
    category: '水果',
    price: 12.80,
    original_price: 15.00,
    images: ['/images/products/product6.jpg'],
    description: '正宗红富士苹果，果肉脆甜多汁，口感爽脆，营养丰富。',
    specification: '1kg/份',
    stock: 100,
    sales: 890,
    origin: '陕西延安',
    farmer: { farmer_id: 104, farmer_name: '赵农户', farmer_avatar: '/images/avatars/farmer4.jpg', verified: true },
    status: 'on_sale',
    created_at: '2025-01-06 08:30:00',
    updated_at: '2025-01-25 10:00:00'
  },
  {
    product_id: 7,
    product_name: '海南香蕉',
    category: '水果',
    price: 5.90,
    original_price: 7.50,
    images: ['/images/products/product7.jpg'],
    description: '海南进口香蕉，果肉香甜软糯，富含钾元素，口感极佳。',
    specification: '500g/份',
    stock: 150,
    sales: 654,
    origin: '海南三亚',
    farmer: { farmer_id: 104, farmer_name: '赵农户', farmer_avatar: '/images/avatars/farmer4.jpg', verified: true },
    status: 'on_sale',
    created_at: '2025-01-07 09:30:00',
    updated_at: '2025-01-26 11:30:00'
  },
  {
    product_id: 8,
    product_name: '新疆哈密瓜',
    category: '水果',
    price: 18.00,
    original_price: 22.00,
    images: ['/images/products/product8.jpg'],
    description: '新疆特产哈密瓜，果肉橙黄，甜度高，香气浓郁，口感绝佳。',
    specification: '1个/份',
    stock: 40,
    sales: 234,
    origin: '新疆哈密',
    farmer: { farmer_id: 105, farmer_name: '孙农户', farmer_avatar: '/images/avatars/farmer5.jpg', verified: true },
    status: 'on_sale',
    created_at: '2025-01-08 10:30:00',
    updated_at: '2025-01-27 12:30:00'
  },
  {
    product_id: 9,
    product_name: '四川柑橘',
    category: '水果',
    price: 8.50,
    original_price: 10.00,
    images: ['/images/products/product9.jpg'],
    description: '四川优质柑橘，果肉饱满多汁，酸甜适中，维生素C丰富。',
    specification: '1kg/份',
    stock: 90,
    sales: 478,
    origin: '四川眉山',
    farmer: { farmer_id: 105, farmer_name: '孙农户', farmer_avatar: '/images/avatars/farmer5.jpg', verified: true },
    status: 'on_sale',
    created_at: '2025-01-09 11:30:00',
    updated_at: '2025-01-28 13:00:00'
  },
  {
    product_id: 10,
    product_name: '云南蓝莓',
    category: '水果',
    price: 25.00,
    original_price: 30.00,
    images: ['/images/products/product10.jpg'],
    description: '云南高原蓝莓，果实饱满，口感酸甜，富含花青素，抗氧化佳品。',
    specification: '125g/盒',
    stock: 50,
    sales: 312,
    origin: '云南昆明',
    farmer: { farmer_id: 106, farmer_name: '周农户', farmer_avatar: '/images/avatars/farmer6.jpg', verified: true },
    status: 'on_sale',
    created_at: '2025-01-10 12:30:00',
    updated_at: '2025-01-29 14:00:00'
  },
  {
    product_id: 11,
    product_name: '东北大米',
    category: '粮食',
    price: 6.80,
    original_price: 8.50,
    images: ['/images/products/product11.jpg'],
    description: '东北优质大米，颗粒饱满，口感软糯，米香浓郁。',
    specification: '2.5kg/袋',
    stock: 80,
    sales: 567,
    origin: '黑龙江五常',
    farmer: { farmer_id: 107, farmer_name: '吴农户', farmer_avatar: '/images/avatars/farmer7.jpg', verified: true },
    status: 'on_sale',
    created_at: '2025-01-11 08:00:00',
    updated_at: '2025-01-30 10:30:00'
  },
  {
    product_id: 12,
    product_name: '山西小米',
    category: '粮食',
    price: 15.80,
    original_price: 18.00,
    images: ['/images/products/product12.jpg'],
    description: '山西特产小米，色泽金黄，口感香糯，营养丰富，易于消化。',
    specification: '1kg/袋',
    stock: 60,
    sales: 345,
    origin: '山西沁县',
    farmer: { farmer_id: 107, farmer_name: '吴农户', farmer_avatar: '/images/avatars/farmer7.jpg', verified: true },
    status: 'on_sale',
    created_at: '2025-01-12 09:00:00',
    updated_at: '2025-01-31 11:00:00'
  },
  {
    product_id: 13,
    product_name: '河北玉米',
    category: '粮食',
    price: 4.20,
    original_price: 5.50,
    images: ['/images/products/product13.jpg'],
    description: '河北甜玉米，颗粒饱满，口感香甜，富含膳食纤维。',
    specification: '500g/份',
    stock: 100,
    sales: 678,
    origin: '河北保定',
    farmer: { farmer_id: 108, farmer_name: '郑农户', farmer_avatar: '/images/avatars/farmer8.jpg', verified: true },
    status: 'on_sale',
    created_at: '2025-01-13 10:00:00',
    updated_at: '2025-02-01 12:00:00'
  },
  {
    product_id: 14,
    product_name: '湖北绿豆',
    category: '粮食',
    price: 9.50,
    original_price: 11.00,
    images: ['/images/products/product14.jpg'],
    description: '湖北优质绿豆，颗粒饱满，易煮烂，清热解毒，夏季佳品。',
    specification: '500g/袋',
    stock: 70,
    sales: 423,
    origin: '湖北荆州',
    farmer: { farmer_id: 108, farmer_name: '郑农户', farmer_avatar: '/images/avatars/farmer8.jpg', verified: true },
    status: 'on_sale',
    created_at: '2025-01-14 11:00:00',
    updated_at: '2025-02-02 13:00:00'
  },
  {
    product_id: 15,
    product_name: '河南黄豆',
    category: '粮食',
    price: 7.80,
    original_price: 9.50,
    images: ['/images/products/product15.jpg'],
    description: '河南优质黄豆，颗粒圆润，蛋白质含量高，适合制作豆制品。',
    specification: '1kg/袋',
    stock: 90,
    sales: 456,
    origin: '河南周口',
    farmer: { farmer_id: 109, farmer_name: '冯农户', farmer_avatar: '/images/avatars/farmer9.jpg', verified: true },
    status: 'on_sale',
    created_at: '2025-01-15 12:00:00',
    updated_at: '2025-02-03 14:00:00'
  },
  {
    product_id: 16,
    product_name: '土鸡蛋',
    category: '其他',
    price: 1.80,
    original_price: 2.20,
    images: ['/images/products/product16.jpg'],
    description: '农家土鸡蛋，蛋黄橙黄，蛋清浓稠，营养丰富，口感鲜美。',
    specification: '1个/份',
    stock: 200,
    sales: 1234,
    origin: '湖南岳阳',
    farmer: { farmer_id: 110, farmer_name: '陈农户', farmer_avatar: '/images/avatars/farmer10.jpg', verified: true },
    status: 'on_sale',
    created_at: '2025-01-16 08:30:00',
    updated_at: '2025-02-04 10:30:00'
  },
  {
    product_id: 17,
    product_name: '纯天然蜂蜜',
    category: '其他',
    price: 68.00,
    original_price: 78.00,
    images: ['/images/products/product17.jpg'],
    description: '纯天然蜂蜜，色泽金黄，口感香甜，富含多种维生素和矿物质。',
    specification: '500g/瓶',
    stock: 30,
    sales: 234,
    origin: '湖北神农架',
    farmer: { farmer_id: 110, farmer_name: '陈农户', farmer_avatar: '/images/avatars/farmer10.jpg', verified: true },
    status: 'on_sale',
    created_at: '2025-01-17 09:30:00',
    updated_at: '2025-02-05 11:30:00'
  },
  {
    product_id: 18,
    product_name: '有机茶叶',
    category: '其他',
    price: 128.00,
    original_price: 150.00,
    images: ['/images/products/product18.jpg'],
    description: '高山有机茶叶，茶汤清澈，香气高雅，回甘持久，品质上乘。',
    specification: '250g/盒',
    stock: 25,
    sales: 189,
    origin: '福建武夷山',
    farmer: { farmer_id: 111, farmer_name: '褚农户', farmer_avatar: '/images/avatars/farmer11.jpg', verified: true },
    status: 'on_sale',
    created_at: '2025-01-18 10:30:00',
    updated_at: '2025-02-06 12:30:00'
  },
  {
    product_id: 19,
    product_name: '农家腊肉',
    category: '其他',
    price: 45.00,
    original_price: 52.00,
    images: ['/images/products/product19.jpg'],
    description: '传统工艺制作腊肉，肉质紧实，香味浓郁，肥而不腻。',
    specification: '500g/份',
    stock: 40,
    sales: 312,
    origin: '四川遂宁',
    farmer: { farmer_id: 111, farmer_name: '褚农户', farmer_avatar: '/images/avatars/farmer11.jpg', verified: true },
    status: 'on_sale',
    created_at: '2025-01-19 11:30:00',
    updated_at: '2025-02-07 13:30:00'
  },
  {
    product_id: 20,
    product_name: '手工豆腐',
    category: '其他',
    price: 3.50,
    original_price: 4.50,
    images: ['/images/products/product20.jpg'],
    description: '传统手工制作豆腐，质地细嫩，豆香浓郁，营养丰富。',
    specification: '400g/块',
    stock: 80,
    sales: 567,
    origin: '安徽淮南',
    farmer: { farmer_id: 112, farmer_name: '卫农户', farmer_avatar: '/images/avatars/farmer12.jpg', verified: true },
    status: 'on_sale',
    created_at: '2025-01-20 12:30:00',
    updated_at: '2025-02-08 14:30:00'
  }
]

export const orders = [
  {
    order_id: 'ORD202501200001',
    user_id: 1,
    status: 'completed',
    total_amount: 35.60,
    payment_method: 'wechat',
    payment_status: 'paid',
    shipping_address: {
      id: 1,
      name: '张三',
      phone: '138****8888',
      province: '北京市',
      city: '北京市',
      district: '朝阳区',
      detail: '三里屯街道123号',
      is_default: true
    },
    items: [
      { product_id: 1, product_name: '有机小白菜', price: 5.80, quantity: 2, image: '/images/products/product1.jpg' },
      { product_id: 6, product_name: '红富士苹果', price: 12.80, quantity: 2, image: '/images/products/product6.jpg' }
    ],
    created_at: '2025-01-20 14:30:00',
    updated_at: '2025-01-20 16:00:00'
  },
  {
    order_id: 'ORD202501210002',
    user_id: 1,
    status: 'shipped',
    total_amount: 68.00,
    payment_method: 'alipay',
    payment_status: 'paid',
    shipping_address: {
      id: 1,
      name: '张三',
      phone: '138****8888',
      province: '北京市',
      city: '北京市',
      district: '朝阳区',
      detail: '三里屯街道123号',
      is_default: true
    },
    items: [
      { product_id: 17, product_name: '纯天然蜂蜜', price: 68.00, quantity: 1, image: '/images/products/product17.jpg' }
    ],
    created_at: '2025-01-21 10:00:00',
    updated_at: '2025-01-22 09:30:00'
  },
  {
    order_id: 'ORD202501220003',
    user_id: 1,
    status: 'pending',
    total_amount: 24.00,
    payment_method: 'wechat',
    payment_status: 'unpaid',
    shipping_address: {
      id: 2,
      name: '张三',
      phone: '138****8888',
      province: '上海市',
      city: '上海市',
      district: '浦东新区',
      detail: '陆家嘴环路456号',
      is_default: false
    },
    items: [
      { product_id: 11, product_name: '东北大米', price: 6.80, quantity: 2, image: '/images/products/product11.jpg' },
      { product_id: 13, product_name: '河北玉米', price: 4.20, quantity: 2, image: '/images/products/product13.jpg' }
    ],
    created_at: '2025-01-22 15:00:00',
    updated_at: '2025-01-22 15:00:00'
  },
  {
    order_id: 'ORD202501230004',
    user_id: 1,
    status: 'completed',
    total_amount: 18.00,
    payment_method: 'wechat',
    payment_status: 'paid',
    shipping_address: {
      id: 1,
      name: '张三',
      phone: '138****8888',
      province: '北京市',
      city: '北京市',
      district: '朝阳区',
      detail: '三里屯街道123号',
      is_default: true
    },
    items: [
      { product_id: 8, product_name: '新疆哈密瓜', price: 18.00, quantity: 1, image: '/images/products/product8.jpg' }
    ],
    created_at: '2025-01-23 11:00:00',
    updated_at: '2025-01-24 10:00:00'
  },
  {
    order_id: 'ORD202501240005',
    user_id: 1,
    status: 'cancelled',
    total_amount: 128.00,
    payment_method: 'alipay',
    payment_status: 'refunded',
    shipping_address: {
      id: 3,
      name: '张三',
      phone: '138****8888',
      province: '广东省',
      city: '深圳市',
      district: '南山区',
      detail: '科技园南路789号',
      is_default: false
    },
    items: [
      { product_id: 18, product_name: '有机茶叶', price: 128.00, quantity: 1, image: '/images/products/product18.jpg' }
    ],
    created_at: '2025-01-24 09:00:00',
    updated_at: '2025-01-24 10:30:00'
  },
  {
    order_id: 'ORD202501250006',
    user_id: 1,
    status: 'completed',
    total_amount: 45.00,
    payment_method: 'wechat',
    payment_status: 'paid',
    shipping_address: {
      id: 1,
      name: '张三',
      phone: '138****8888',
      province: '北京市',
      city: '北京市',
      district: '朝阳区',
      detail: '三里屯街道123号',
      is_default: true
    },
    items: [
      { product_id: 19, product_name: '农家腊肉', price: 45.00, quantity: 1, image: '/images/products/product19.jpg' }
    ],
    created_at: '2025-01-25 14:00:00',
    updated_at: '2025-01-26 11:00:00'
  },
  {
    order_id: 'ORD202501260007',
    user_id: 1,
    status: 'shipped',
    total_amount: 52.60,
    payment_method: 'alipay',
    payment_status: 'paid',
    shipping_address: {
      id: 2,
      name: '张三',
      phone: '138****8888',
      province: '上海市',
      city: '上海市',
      district: '浦东新区',
      detail: '陆家嘴环路456号',
      is_default: false
    },
    items: [
      { product_id: 3, product_name: '有机西兰花', price: 8.90, quantity: 2, image: '/images/products/product3.jpg' },
      { product_id: 10, product_name: '云南蓝莓', price: 25.00, quantity: 1, image: '/images/products/product10.jpg' },
      { product_id: 16, product_name: '土鸡蛋', price: 1.80, quantity: 5, image: '/images/products/product16.jpg' }
    ],
    created_at: '2025-01-26 10:00:00',
    updated_at: '2025-01-27 09:00:00'
  },
  {
    order_id: 'ORD202501270008',
    user_id: 1,
    status: 'pending',
    total_amount: 13.60,
    payment_method: 'wechat',
    payment_status: 'unpaid',
    shipping_address: {
      id: 1,
      name: '张三',
      phone: '138****8888',
      province: '北京市',
      city: '北京市',
      district: '朝阳区',
      detail: '三里屯街道123号',
      is_default: true
    },
    items: [
      { product_id: 2, product_name: '本地胡萝卜', price: 4.50, quantity: 2, image: '/images/products/product2.jpg' },
      { product_id: 4, product_name: '新鲜黄瓜', price: 3.80, quantity: 1, image: '/images/products/product4.jpg' }
    ],
    created_at: '2025-01-27 16:00:00',
    updated_at: '2025-01-27 16:00:00'
  },
  {
    order_id: 'ORD202501280009',
    user_id: 1,
    status: 'completed',
    total_amount: 27.60,
    payment_method: 'wechat',
    payment_status: 'paid',
    shipping_address: {
      id: 1,
      name: '张三',
      phone: '138****8888',
      province: '北京市',
      city: '北京市',
      district: '朝阳区',
      detail: '三里屯街道123号',
      is_default: true
    },
    items: [
      { product_id: 5, product_name: '有机菠菜', price: 6.50, quantity: 2, image: '/images/products/product5.jpg' },
      { product_id: 7, product_name: '海南香蕉', price: 5.90, quantity: 2, image: '/images/products/product7.jpg' }
    ],
    created_at: '2025-01-28 13:00:00',
    updated_at: '2025-01-29 12:00:00'
  },
  {
    order_id: 'ORD202501290010',
    user_id: 1,
    status: 'completed',
    total_amount: 33.10,
    payment_method: 'alipay',
    payment_status: 'paid',
    shipping_address: {
      id: 3,
      name: '张三',
      phone: '138****8888',
      province: '广东省',
      city: '深圳市',
      district: '南山区',
      detail: '科技园南路789号',
      is_default: false
    },
    items: [
      { product_id: 9, product_name: '四川柑橘', price: 8.50, quantity: 2, image: '/images/products/product9.jpg' },
      { product_id: 12, product_name: '山西小米', price: 15.80, quantity: 1, image: '/images/products/product12.jpg' }
    ],
    created_at: '2025-01-29 11:00:00',
    updated_at: '2025-01-30 10:00:00'
  }
]

export const categories = [
  { id: 1, name: '蔬菜', icon: 'vegetable' },
  { id: 2, name: '水果', icon: 'fruit' },
  { id: 3, name: '粮食', icon: 'grain' },
  { id: 4, name: '其他', icon: 'other' }
]

export const addresses = [
  {
    id: 1,
    name: '张三',
    phone: '138****8888',
    province: '北京市',
    city: '北京市',
    district: '朝阳区',
    detail: '三里屯街道123号',
    is_default: true
  },
  {
    id: 2,
    name: '张三',
    phone: '138****8888',
    province: '上海市',
    city: '上海市',
    district: '浦东新区',
    detail: '陆家嘴环路456号',
    is_default: false
  },
  {
    id: 3,
    name: '张三',
    phone: '138****8888',
    province: '广东省',
    city: '深圳市',
    district: '南山区',
    detail: '科技园南路789号',
    is_default: false
  }
]
